//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbiResourceWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.frsoft.com/webservices", ConfigurationName="NbiResourceWS.ResourceWS")]
    public interface ResourceWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/Load", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiResourceWS.Resource[]> LoadAsync(NbiResourceWS.AuthenticationHeader header, string resource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/LoadWithSegment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiResourceWS.Resource> LoadWithSegmentAsync(NbiResourceWS.AuthenticationHeader header, string resource, int segmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiResourceWS.Resource> SaveAsync(NbiResourceWS.AuthenticationHeader header, NbiResourceWS.Resource r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/Query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiResourceWS.Resource[]> QueryAsync(NbiResourceWS.AuthenticationHeader header, NbiResourceWS.ResourceCriteria[] criteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/QueryWithSegment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiResourceWS.Resource[]> QueryWithSegmentAsync(NbiResourceWS.AuthenticationHeader header, NbiResourceWS.ResourceCriteria[] criteria, int segmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/GetTimeCharges", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiResourceWS.TimeCharge[]> GetTimeChargesAsync(NbiResourceWS.AuthenticationHeader header, int resourceID, int segmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/GetTimeChargesByDates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiResourceWS.TimeCharge[]> GetTimeChargesByDatesAsync(NbiResourceWS.AuthenticationHeader header, int resourceID, int segmentID, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/SaveTimeChargeForResource", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiResourceWS.TimeCharge> SaveTimeChargeForResourceAsync(NbiResourceWS.AuthenticationHeader header, int resourceID, NbiResourceWS.TimeCharge sdkTC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/SaveTimeCharge", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiResourceWS.TimeCharge> SaveTimeChargeAsync(NbiResourceWS.AuthenticationHeader header, NbiResourceWS.TimeCharge sdkTC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/SaveTimeChargeArray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiResourceWS.SaveResult[]> SaveTimeChargeArrayAsync(NbiResourceWS.AuthenticationHeader header, NbiResourceWS.TimeCharge[] sdkTCs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/DeleteTimeCharge", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task DeleteTimeChargeAsync(NbiResourceWS.AuthenticationHeader header, NbiResourceWS.TimeCharge sdkTC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/GetResourceUnavailability", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiResourceWS.ResourceException[]> GetResourceUnavailabilityAsync(NbiResourceWS.AuthenticationHeader header, int resourceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/SaveResourceUnavailability", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resource[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiResourceWS.ResourceException> SaveResourceUnavailabilityAsync(NbiResourceWS.AuthenticationHeader header, int resourceID, NbiResourceWS.ResourceException sdkException);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public partial class AuthenticationHeader
    {
        
        private string serverField;
        
        private string databaseField;
        
        private string userNameField;
        
        private string passwordField;
        
        private string passKeyField;
        
        private string hostNameField;
        
        private string openObjectIdField;
        
        private bool useSSOAuthenticationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Server
        {
            get
            {
                return this.serverField;
            }
            set
            {
                this.serverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Database
        {
            get
            {
                return this.databaseField;
            }
            set
            {
                this.databaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PassKey
        {
            get
            {
                return this.passKeyField;
            }
            set
            {
                this.passKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string HostName
        {
            get
            {
                return this.hostNameField;
            }
            set
            {
                this.hostNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string OpenObjectId
        {
            get
            {
                return this.openObjectIdField;
            }
            set
            {
                this.openObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool UseSSOAuthentication
        {
            get
            {
                return this.useSSOAuthenticationField;
            }
            set
            {
                this.useSSOAuthenticationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public partial class SaveResult
    {
        
        private int idField;
        
        private string valueField;
        
        private string resultField;
        
        private bool successfulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool Successful
        {
            get
            {
                return this.successfulField;
            }
            set
            {
                this.successfulField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResourceCriteria))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public abstract partial class Criteria
    {
        
        private LOGICAL_OPERATORS logicalOperatorField;
        
        private OPERATORS operatorField;
        
        private object fieldValueField;
        
        private DATA_TYPE_ENUM dataTypeField;
        
        private int fieldIDField;
        
        private string fieldNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LOGICAL_OPERATORS LogicalOperator
        {
            get
            {
                return this.logicalOperatorField;
            }
            set
            {
                this.logicalOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OPERATORS Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object FieldValue
        {
            get
            {
                return this.fieldValueField;
            }
            set
            {
                this.fieldValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DATA_TYPE_ENUM DataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int FieldID
        {
            get
            {
                return this.fieldIDField;
            }
            set
            {
                this.fieldIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FieldName
        {
            get
            {
                return this.fieldNameField;
            }
            set
            {
                this.fieldNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public enum LOGICAL_OPERATORS
    {
        
        /// <remarks/>
        AND,
        
        /// <remarks/>
        OR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public enum OPERATORS
    {
        
        /// <remarks/>
        EQUAL,
        
        /// <remarks/>
        NOT_EQUAL,
        
        /// <remarks/>
        ISLIKE,
        
        /// <remarks/>
        GREATER,
        
        /// <remarks/>
        LESS,
        
        /// <remarks/>
        GREATER_OR_EQUAL,
        
        /// <remarks/>
        LESS_OR_EQUAL,
        
        /// <remarks/>
        ISNULL,
        
        /// <remarks/>
        ISNOTLIKE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public enum DATA_TYPE_ENUM
    {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        STRING,
        
        /// <remarks/>
        NUMBER,
        
        /// <remarks/>
        BOOLEAN,
        
        /// <remarks/>
        DATE,
        
        /// <remarks/>
        TIME,
        
        /// <remarks/>
        EMAIL,
        
        /// <remarks/>
        CURRENCY,
        
        /// <remarks/>
        PERCENT,
        
        /// <remarks/>
        OBJECT,
        
        /// <remarks/>
        WHOLE_NUMBER,
        
        /// <remarks/>
        DATE_TIME,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public partial class ResourceCriteria : Criteria
    {
        
        private FIELDS fieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FIELDS Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public enum FIELDS
    {
        
        /// <remarks/>
        SEGMENT,
        
        /// <remarks/>
        RESOURCEID,
        
        /// <remarks/>
        RESOURCE_NUMBER,
        
        /// <remarks/>
        TYPE_CODE,
        
        /// <remarks/>
        TYPE_DESCRIPTION,
        
        /// <remarks/>
        FIRST_NAME,
        
        /// <remarks/>
        LAST_NAME,
        
        /// <remarks/>
        ADDRESS1,
        
        /// <remarks/>
        ADDRESS2,
        
        /// <remarks/>
        CITY,
        
        /// <remarks/>
        STATE,
        
        /// <remarks/>
        ZIP,
        
        /// <remarks/>
        HOME_PHONE,
        
        /// <remarks/>
        EMERGENCY_CONTACT,
        
        /// <remarks/>
        EMERGENCY_PHONE,
        
        /// <remarks/>
        WORK_PHONE,
        
        /// <remarks/>
        PAGER,
        
        /// <remarks/>
        EMAIL,
        
        /// <remarks/>
        ACCOUNT_CODE,
        
        /// <remarks/>
        ACCOUNT_DESCRIPTION,
        
        /// <remarks/>
        SITE_CODE,
        
        /// <remarks/>
        SITE_NAME,
        
        /// <remarks/>
        BUILDING_CODE,
        
        /// <remarks/>
        BUILDING_NAME,
        
        /// <remarks/>
        LOCATION_CODE,
        
        /// <remarks/>
        LOCATION_DESCRIPTION,
        
        /// <remarks/>
        SHOP_CODE,
        
        /// <remarks/>
        SHOP_DESCRIPTION,
        
        /// <remarks/>
        AREA_CODE,
        
        /// <remarks/>
        AREA_DESCRIPTION,
        
        /// <remarks/>
        SKILL_CODE,
        
        /// <remarks/>
        SKILL_DESCRIPTION,
        
        /// <remarks/>
        SHIFT_CODE,
        
        /// <remarks/>
        SHIFT_DESCRIPTION,
        
        /// <remarks/>
        SKILL_LEVEL_CODE,
        
        /// <remarks/>
        SKILL_LEVEL_DESCRIPTION,
        
        /// <remarks/>
        CHARGE_RATE,
        
        /// <remarks/>
        START_DATE,
        
        /// <remarks/>
        LAST_REVIEW_DATE,
        
        /// <remarks/>
        PAGER_EMAIL,
        
        /// <remarks/>
        STATUS_CODE,
        
        /// <remarks/>
        STATUS_DESCRIPTION,
        
        /// <remarks/>
        UDF1,
        
        /// <remarks/>
        UDF2,
        
        /// <remarks/>
        UDF3,
        
        /// <remarks/>
        UDF4,
        
        /// <remarks/>
        UDF5,
        
        /// <remarks/>
        UDF6,
        
        /// <remarks/>
        UDF7,
        
        /// <remarks/>
        UDF8,
        
        /// <remarks/>
        UDF9,
        
        /// <remarks/>
        UDF10,
        
        /// <remarks/>
        NOTES,
        
        /// <remarks/>
        DATE_UPDATED,
        
        /// <remarks/>
        DATE_CREATED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public partial class CustomField
    {
        
        private int fieldIdField;
        
        private int parentFieldIdField;
        
        private string nameField;
        
        private object valueField;
        
        private string valueDescriptionField;
        
        private bool isCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FieldId
        {
            get
            {
                return this.fieldIdField;
            }
            set
            {
                this.fieldIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ParentFieldId
        {
            get
            {
                return this.parentFieldIdField;
            }
            set
            {
                this.parentFieldIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public object Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ValueDescription
        {
            get
            {
                return this.valueDescriptionField;
            }
            set
            {
                this.valueDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsCode
        {
            get
            {
                return this.isCodeField;
            }
            set
            {
                this.isCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResourceException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeCharge))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SDKBaseUpdate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Resource))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public abstract partial class SDKBase
    {
        
        private int segmentIDField;
        
        private int fieldIdField;
        
        private MODULES moduleIdField;
        
        private bool validateForDataImportField;
        
        private int keyIDField;
        
        private CustomField[] customFieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SegmentID
        {
            get
            {
                return this.segmentIDField;
            }
            set
            {
                this.segmentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int FieldId
        {
            get
            {
                return this.fieldIdField;
            }
            set
            {
                this.fieldIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MODULES ModuleId
        {
            get
            {
                return this.moduleIdField;
            }
            set
            {
                this.moduleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ValidateForDataImport
        {
            get
            {
                return this.validateForDataImportField;
            }
            set
            {
                this.validateForDataImportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int KeyID
        {
            get
            {
                return this.keyIDField;
            }
            set
            {
                this.keyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public CustomField[] CustomFields
        {
            get
            {
                return this.customFieldsField;
            }
            set
            {
                this.customFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public enum MODULES
    {
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        TASKS,
        
        /// <remarks/>
        RESOURCES,
        
        /// <remarks/>
        ASSETS,
        
        /// <remarks/>
        MATERIALS,
        
        /// <remarks/>
        WORK_ORDERS,
        
        /// <remarks/>
        VENDORS,
        
        /// <remarks/>
        TIME_CHARGES,
        
        /// <remarks/>
        PM,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        PURCHASING,
        
        /// <remarks/>
        REPORTING,
        
        /// <remarks/>
        REQUISITIONS,
        
        /// <remarks/>
        PM_GENERATE,
        
        /// <remarks/>
        WEB_REQUEST,
        
        /// <remarks/>
        WO_SURVEY,
        
        /// <remarks/>
        QUICK_CLOSE,
        
        /// <remarks/>
        EMAIL_RESPONSE,
        
        /// <remarks/>
        UPGRADE,
        
        /// <remarks/>
        GENERAL,
        
        /// <remarks/>
        DOCUMENT_UPLOAD,
        
        /// <remarks/>
        CONTRACTS,
        
        /// <remarks/>
        PO_GENERATE,
        
        /// <remarks/>
        REQUISITION_GENERATE,
        
        /// <remarks/>
        REQUESTERS,
        
        /// <remarks/>
        CUSTOMERS,
        
        /// <remarks/>
        BLANKET_ORDERS,
        
        /// <remarks/>
        SUB_TASKS,
        
        /// <remarks/>
        DISPATCH,
        
        /// <remarks/>
        DEPARTMENTS,
        
        /// <remarks/>
        UTILITY,
        
        /// <remarks/>
        SAFETY_INCIDENTS,
        
        /// <remarks/>
        INFO_CENTER,
        
        /// <remarks/>
        HIS_LINKS,
        
        /// <remarks/>
        HL7,
        
        /// <remarks/>
        SDK,
        
        /// <remarks/>
        AUTOPRINT,
        
        /// <remarks/>
        ASSET_GROUPS,
        
        /// <remarks/>
        TASK_GROUPS,
        
        /// <remarks/>
        MED_TESTER,
        
        /// <remarks/>
        HIPAA_SURVEY,
        
        /// <remarks/>
        AUTO_ASSIGNMENT,
        
        /// <remarks/>
        ECRI_ALERTS,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        SOURCEBASE_CODES,
        
        /// <remarks/>
        UMDNS_CODES,
        
        /// <remarks/>
        CONTRACT_PAYMENTS,
        
        /// <remarks/>
        CUSTOMER_CONTACTS,
        
        /// <remarks/>
        DASHBOARD,
        
        /// <remarks/>
        DISCUSSIONS,
        
        /// <remarks/>
        MATERIAL_ISSUES,
        
        /// <remarks/>
        MATERIAL_RECEIPTS,
        
        /// <remarks/>
        DOWNTIMES,
        
        /// <remarks/>
        USER_FIELDS,
        
        /// <remarks/>
        WO_TASKS,
        
        /// <remarks/>
        WO_ASSIGNMENTS,
        
        /// <remarks/>
        ASSET_CONTACTS,
        
        /// <remarks/>
        ASSET_COMPONENTS,
        
        /// <remarks/>
        WO_ASSETS,
        
        /// <remarks/>
        PM_ASSETS,
        
        /// <remarks/>
        CONTRACT_ASSETS,
        
        /// <remarks/>
        ASSET_MATERIALS,
        
        /// <remarks/>
        PM_MATERIALS,
        
        /// <remarks/>
        PARTS_SOURCE,
        
        /// <remarks/>
        DATASOURCE,
        
        /// <remarks/>
        SAVED_QUERIES,
        
        /// <remarks/>
        REPORT_DEFINITIONS,
        
        /// <remarks/>
        PM_ASSIGNMENTS,
        
        /// <remarks/>
        PM_EXCEPTIONS,
        
        /// <remarks/>
        PM_PROCEDURES,
        
        /// <remarks/>
        TASK_MATERIALS,
        
        /// <remarks/>
        VENDOR_MODELS,
        
        /// <remarks/>
        PATIENT,
        
        /// <remarks/>
        USER_PROFILES,
        
        /// <remarks/>
        PORTALS,
        
        /// <remarks/>
        INSPECTIONS,
        
        /// <remarks/>
        SEGMENTS,
        
        /// <remarks/>
        MESSAGE_CENTER,
        
        /// <remarks/>
        SEGMENTFIELDS,
        
        /// <remarks/>
        STORED_PROCEDURE_SCHEDULE,
        
        /// <remarks/>
        SCHEDULES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public partial class ResourceException : SDKBase
    {
        
        private int exceptionIDField;
        
        private string resourceNumberField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private string typeCodeField;
        
        private string typeIDField;
        
        private string typeDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ExceptionID
        {
            get
            {
                return this.exceptionIDField;
            }
            set
            {
                this.exceptionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResourceNumber
        {
            get
            {
                return this.resourceNumberField;
            }
            set
            {
                this.resourceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TypeCode
        {
            get
            {
                return this.typeCodeField;
            }
            set
            {
                this.typeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TypeID
        {
            get
            {
                return this.typeIDField;
            }
            set
            {
                this.typeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TypeDescription
        {
            get
            {
                return this.typeDescriptionField;
            }
            set
            {
                this.typeDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public partial class TimeCharge : SDKBase
    {
        
        private int timeChargeIDField;
        
        private string resourceNumberField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string resourceNameField;
        
        private string hoursTypeCodeField;
        
        private string hoursTypeDescriptionField;
        
        private double hoursField;
        
        private System.DateTime dateIssuedField;
        
        private System.DateTime stopTimeField;
        
        private double totalCostField;
        
        private string commentsField;
        
        private int workOrderNumberField;
        
        private string assetNumberField;
        
        private string assetDescriptionField;
        
        private string accountNumberField;
        
        private string accountDescriptionField;
        
        private string billableTypeCodeField;
        
        private string billableTypeDescriptionField;
        
        private string assetGroupNumberField;
        
        private string wODescriptionField;
        
        private string resourceShopDescriptionField;
        
        private int taskNumberField;
        
        private System.DateTime dateUpdatedField;
        
        private System.DateTime dateCreatedField;
        
        private string costCenterCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TimeChargeID
        {
            get
            {
                return this.timeChargeIDField;
            }
            set
            {
                this.timeChargeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResourceNumber
        {
            get
            {
                return this.resourceNumberField;
            }
            set
            {
                this.resourceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ResourceName
        {
            get
            {
                return this.resourceNameField;
            }
            set
            {
                this.resourceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string HoursTypeCode
        {
            get
            {
                return this.hoursTypeCodeField;
            }
            set
            {
                this.hoursTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string HoursTypeDescription
        {
            get
            {
                return this.hoursTypeDescriptionField;
            }
            set
            {
                this.hoursTypeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double Hours
        {
            get
            {
                return this.hoursField;
            }
            set
            {
                this.hoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime DateIssued
        {
            get
            {
                return this.dateIssuedField;
            }
            set
            {
                this.dateIssuedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime StopTime
        {
            get
            {
                return this.stopTimeField;
            }
            set
            {
                this.stopTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double TotalCost
        {
            get
            {
                return this.totalCostField;
            }
            set
            {
                this.totalCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int WorkOrderNumber
        {
            get
            {
                return this.workOrderNumberField;
            }
            set
            {
                this.workOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string AssetNumber
        {
            get
            {
                return this.assetNumberField;
            }
            set
            {
                this.assetNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string AssetDescription
        {
            get
            {
                return this.assetDescriptionField;
            }
            set
            {
                this.assetDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string AccountDescription
        {
            get
            {
                return this.accountDescriptionField;
            }
            set
            {
                this.accountDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string BillableTypeCode
        {
            get
            {
                return this.billableTypeCodeField;
            }
            set
            {
                this.billableTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string BillableTypeDescription
        {
            get
            {
                return this.billableTypeDescriptionField;
            }
            set
            {
                this.billableTypeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string AssetGroupNumber
        {
            get
            {
                return this.assetGroupNumberField;
            }
            set
            {
                this.assetGroupNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string WODescription
        {
            get
            {
                return this.wODescriptionField;
            }
            set
            {
                this.wODescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string ResourceShopDescription
        {
            get
            {
                return this.resourceShopDescriptionField;
            }
            set
            {
                this.resourceShopDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int TaskNumber
        {
            get
            {
                return this.taskNumberField;
            }
            set
            {
                this.taskNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public System.DateTime DateUpdated
        {
            get
            {
                return this.dateUpdatedField;
            }
            set
            {
                this.dateUpdatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public System.DateTime DateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string CostCenterCode
        {
            get
            {
                return this.costCenterCodeField;
            }
            set
            {
                this.costCenterCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Resource))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public abstract partial class SDKBaseUpdate : SDKBase
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public partial class Resource : SDKBaseUpdate
    {
        
        private int resourceIDField;
        
        private string resourceNumberField;
        
        private string typeCodeField;
        
        private string typeDescriptionField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string nameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string homePhoneField;
        
        private string emergencyContactField;
        
        private string emergencyContactPhoneField;
        
        private string workPhoneField;
        
        private string workPagerField;
        
        private string accountCodeField;
        
        private string accountDescriptionField;
        
        private string siteCodeField;
        
        private string siteNameField;
        
        private string buildingCodeField;
        
        private string buildingNameField;
        
        private string locationCodeField;
        
        private string locationDescriptionField;
        
        private string shopCodeField;
        
        private string shopDescriptionField;
        
        private string areaCodeField;
        
        private string areaDescriptionField;
        
        private string skillCodeField;
        
        private string skillDescriptionField;
        
        private string skillLevelCodeField;
        
        private string shiftCodeField;
        
        private string shiftDescriptionField;
        
        private double chargeRateField;
        
        private System.DateTime startDateField;
        
        private System.DateTime lastReviewDateField;
        
        private string emailField;
        
        private string pagerEmailField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private string userField1Field;
        
        private string userField2Field;
        
        private string userField3Field;
        
        private string userField4Field;
        
        private string userField5Field;
        
        private string userField6Field;
        
        private string userField7Field;
        
        private string userField8Field;
        
        private string userField9Field;
        
        private string userField10Field;
        
        private string notesField;
        
        private System.Nullable<System.DateTime> dateCreatedField;
        
        private System.Nullable<System.DateTime> dateUpdatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ResourceID
        {
            get
            {
                return this.resourceIDField;
            }
            set
            {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResourceNumber
        {
            get
            {
                return this.resourceNumberField;
            }
            set
            {
                this.resourceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TypeCode
        {
            get
            {
                return this.typeCodeField;
            }
            set
            {
                this.typeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TypeDescription
        {
            get
            {
                return this.typeDescriptionField;
            }
            set
            {
                this.typeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string HomePhone
        {
            get
            {
                return this.homePhoneField;
            }
            set
            {
                this.homePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string EmergencyContact
        {
            get
            {
                return this.emergencyContactField;
            }
            set
            {
                this.emergencyContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string EmergencyContactPhone
        {
            get
            {
                return this.emergencyContactPhoneField;
            }
            set
            {
                this.emergencyContactPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string WorkPhone
        {
            get
            {
                return this.workPhoneField;
            }
            set
            {
                this.workPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string WorkPager
        {
            get
            {
                return this.workPagerField;
            }
            set
            {
                this.workPagerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string AccountCode
        {
            get
            {
                return this.accountCodeField;
            }
            set
            {
                this.accountCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string AccountDescription
        {
            get
            {
                return this.accountDescriptionField;
            }
            set
            {
                this.accountDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string SiteCode
        {
            get
            {
                return this.siteCodeField;
            }
            set
            {
                this.siteCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string SiteName
        {
            get
            {
                return this.siteNameField;
            }
            set
            {
                this.siteNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string BuildingCode
        {
            get
            {
                return this.buildingCodeField;
            }
            set
            {
                this.buildingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string BuildingName
        {
            get
            {
                return this.buildingNameField;
            }
            set
            {
                this.buildingNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string LocationCode
        {
            get
            {
                return this.locationCodeField;
            }
            set
            {
                this.locationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string LocationDescription
        {
            get
            {
                return this.locationDescriptionField;
            }
            set
            {
                this.locationDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string ShopCode
        {
            get
            {
                return this.shopCodeField;
            }
            set
            {
                this.shopCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string ShopDescription
        {
            get
            {
                return this.shopDescriptionField;
            }
            set
            {
                this.shopDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string AreaCode
        {
            get
            {
                return this.areaCodeField;
            }
            set
            {
                this.areaCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string AreaDescription
        {
            get
            {
                return this.areaDescriptionField;
            }
            set
            {
                this.areaDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string SkillCode
        {
            get
            {
                return this.skillCodeField;
            }
            set
            {
                this.skillCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string SkillDescription
        {
            get
            {
                return this.skillDescriptionField;
            }
            set
            {
                this.skillDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string SkillLevelCode
        {
            get
            {
                return this.skillLevelCodeField;
            }
            set
            {
                this.skillLevelCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string ShiftCode
        {
            get
            {
                return this.shiftCodeField;
            }
            set
            {
                this.shiftCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string ShiftDescription
        {
            get
            {
                return this.shiftDescriptionField;
            }
            set
            {
                this.shiftDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public double ChargeRate
        {
            get
            {
                return this.chargeRateField;
            }
            set
            {
                this.chargeRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public System.DateTime LastReviewDate
        {
            get
            {
                return this.lastReviewDateField;
            }
            set
            {
                this.lastReviewDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string PagerEmail
        {
            get
            {
                return this.pagerEmailField;
            }
            set
            {
                this.pagerEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string UserField1
        {
            get
            {
                return this.userField1Field;
            }
            set
            {
                this.userField1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string UserField2
        {
            get
            {
                return this.userField2Field;
            }
            set
            {
                this.userField2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string UserField3
        {
            get
            {
                return this.userField3Field;
            }
            set
            {
                this.userField3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string UserField4
        {
            get
            {
                return this.userField4Field;
            }
            set
            {
                this.userField4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string UserField5
        {
            get
            {
                return this.userField5Field;
            }
            set
            {
                this.userField5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string UserField6
        {
            get
            {
                return this.userField6Field;
            }
            set
            {
                this.userField6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string UserField7
        {
            get
            {
                return this.userField7Field;
            }
            set
            {
                this.userField7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string UserField8
        {
            get
            {
                return this.userField8Field;
            }
            set
            {
                this.userField8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string UserField9
        {
            get
            {
                return this.userField9Field;
            }
            set
            {
                this.userField9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string UserField10
        {
            get
            {
                return this.userField10Field;
            }
            set
            {
                this.userField10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=52)]
        public System.Nullable<System.DateTime> DateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=53)]
        public System.Nullable<System.DateTime> DateUpdated
        {
            get
            {
                return this.dateUpdatedField;
            }
            set
            {
                this.dateUpdatedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ResourceWSChannel : NbiResourceWS.ResourceWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ResourceWSClient : System.ServiceModel.ClientBase<NbiResourceWS.ResourceWS>, NbiResourceWS.ResourceWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ResourceWSClient(EndpointConfiguration endpointConfiguration) : 
                base(ResourceWSClient.GetBindingForEndpoint(endpointConfiguration), ResourceWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ResourceWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ResourceWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ResourceWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ResourceWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ResourceWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<NbiResourceWS.Resource[]> LoadAsync(NbiResourceWS.AuthenticationHeader header, string resource)
        {
            return base.Channel.LoadAsync(header, resource);
        }
        
        public System.Threading.Tasks.Task<NbiResourceWS.Resource> LoadWithSegmentAsync(NbiResourceWS.AuthenticationHeader header, string resource, int segmentID)
        {
            return base.Channel.LoadWithSegmentAsync(header, resource, segmentID);
        }
        
        public System.Threading.Tasks.Task<NbiResourceWS.Resource> SaveAsync(NbiResourceWS.AuthenticationHeader header, NbiResourceWS.Resource r)
        {
            return base.Channel.SaveAsync(header, r);
        }
        
        public System.Threading.Tasks.Task<NbiResourceWS.Resource[]> QueryAsync(NbiResourceWS.AuthenticationHeader header, NbiResourceWS.ResourceCriteria[] criteria)
        {
            return base.Channel.QueryAsync(header, criteria);
        }
        
        public System.Threading.Tasks.Task<NbiResourceWS.Resource[]> QueryWithSegmentAsync(NbiResourceWS.AuthenticationHeader header, NbiResourceWS.ResourceCriteria[] criteria, int segmentID)
        {
            return base.Channel.QueryWithSegmentAsync(header, criteria, segmentID);
        }
        
        public System.Threading.Tasks.Task<NbiResourceWS.TimeCharge[]> GetTimeChargesAsync(NbiResourceWS.AuthenticationHeader header, int resourceID, int segmentID)
        {
            return base.Channel.GetTimeChargesAsync(header, resourceID, segmentID);
        }
        
        public System.Threading.Tasks.Task<NbiResourceWS.TimeCharge[]> GetTimeChargesByDatesAsync(NbiResourceWS.AuthenticationHeader header, int resourceID, int segmentID, System.DateTime startDate, System.DateTime endDate)
        {
            return base.Channel.GetTimeChargesByDatesAsync(header, resourceID, segmentID, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<NbiResourceWS.TimeCharge> SaveTimeChargeForResourceAsync(NbiResourceWS.AuthenticationHeader header, int resourceID, NbiResourceWS.TimeCharge sdkTC)
        {
            return base.Channel.SaveTimeChargeForResourceAsync(header, resourceID, sdkTC);
        }
        
        public System.Threading.Tasks.Task<NbiResourceWS.TimeCharge> SaveTimeChargeAsync(NbiResourceWS.AuthenticationHeader header, NbiResourceWS.TimeCharge sdkTC)
        {
            return base.Channel.SaveTimeChargeAsync(header, sdkTC);
        }
        
        public System.Threading.Tasks.Task<NbiResourceWS.SaveResult[]> SaveTimeChargeArrayAsync(NbiResourceWS.AuthenticationHeader header, NbiResourceWS.TimeCharge[] sdkTCs)
        {
            return base.Channel.SaveTimeChargeArrayAsync(header, sdkTCs);
        }
        
        public System.Threading.Tasks.Task DeleteTimeChargeAsync(NbiResourceWS.AuthenticationHeader header, NbiResourceWS.TimeCharge sdkTC)
        {
            return base.Channel.DeleteTimeChargeAsync(header, sdkTC);
        }
        
        public System.Threading.Tasks.Task<NbiResourceWS.ResourceException[]> GetResourceUnavailabilityAsync(NbiResourceWS.AuthenticationHeader header, int resourceID)
        {
            return base.Channel.GetResourceUnavailabilityAsync(header, resourceID);
        }
        
        public System.Threading.Tasks.Task<NbiResourceWS.ResourceException> SaveResourceUnavailabilityAsync(NbiResourceWS.AuthenticationHeader header, int resourceID, NbiResourceWS.ResourceException sdkException)
        {
            return base.Channel.SaveResourceUnavailabilityAsync(header, resourceID, sdkException);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ResourceWS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ResourceWS1))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ResourceWS))
            {
                return new System.ServiceModel.EndpointAddress("https://rwjbh.tmsonline.com/tmsconnect/ResourceWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ResourceWS1))
            {
                return new System.ServiceModel.EndpointAddress("https://rwjbh.tmsonline.com/tmsconnect/ResourceWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ResourceWS,
            
            ResourceWS1,
        }
    }
}
