CREATE TABLE [dbo].[Organization] (
    [Orgkey]            UNIQUEIDENTIFIER CONSTRAINT [DF_Organization_Orgkey] DEFAULT (newid()) NOT NULL,
    [ClientNo]          INT              IDENTITY (1, 1) NOT NULL,
    [Name]              NVARCHAR (250)   NULL,
	[Code]          NVARCHAR (50)    NULL,
    [Latitude]          NVARCHAR (50)    NULL,
    [Longitude]         NVARCHAR (50)    NULL,
    [Email]             NVARCHAR (150)   NULL,
    [City]              NVARCHAR (100)   NULL,
    [State]             NVARCHAR (50)    NULL,
    [Country]           NVARCHAR (150)   NULL,
    [Zip]               NVARCHAR (50)    NULL,
    [logoName]          NVARCHAR (50)    NULL,
    [LogoPath]          NVARCHAR (150)   NULL,
    [IsOutpatient]      BIT              CONSTRAINT [DF_Organization_IsOutpatient] DEFAULT ((0)) NULL,
    [IsActive]          BIT              CONSTRAINT [DF_Organization_IsActive] DEFAULT ((1)) NULL,
    [FileName]          NVARCHAR (50)    NULL,
    [DashBoadImagePath] NVARCHAR (250)   NULL,
    [DbName]            NVARCHAR (20)    NULL,
    [ParentOrgKey]      UNIQUEIDENTIFIER NULL,
    [Address]           NVARCHAR (MAX)   NULL,
    [IsParent]          BIT              CONSTRAINT [DF_Organization_IsParent] DEFAULT ((0)) NULL,
    [IsTmsWo]           BIT              CONSTRAINT [DF_Organization_IsTmsWo] DEFAULT ((0)) NULL,
    [SegmentId]         INT              CONSTRAINT [DF_Organization_SegmentId] DEFAULT ((1)) NULL,
    [Timezone]          NVARCHAR (150)   NULL,
    [CreatedBy]         INT              NOT NULL,
    [CreatedDate]       DATETIME         CONSTRAINT [DF_Originations_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [BaseUrl]           NVARCHAR (150)   NULL,
    [HospitalTypeId]    INT              NULL,
    [FireWatchTimeSlot] INT              CONSTRAINT [DF_Organization_FireWatchTimeSlot] DEFAULT ((4)) NULL,
    [DefaultEPInspection] BIT NULL DEFAULT 0, 
    [NonTrackedEPReportDate] DATETIME NULL, 
    CONSTRAINT [PK_Organization_1] PRIMARY KEY CLUSTERED ([Orgkey] ASC),
    CONSTRAINT [FK_Organization_Organization] FOREIGN KEY ([Orgkey]) REFERENCES [dbo].[Organization] ([Orgkey])
);

