CREATE TABLE [dbo].[OrgSettings](
	[SettingId] [int] IDENTITY(1,1) NOT NULL,
 [AhjFileLimit] BIGINT NULL, 
    [Orgkey] UNIQUEIDENTIFIER NULL, 
    CONSTRAINT [PK_OrgSettings] PRIMARY KEY CLUSTERED 
(
	[SettingId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
