CREATE TABLE [dbo].[UserLogin] (
    [UserLoginId]          BIGINT              IDENTITY (1, 1) NOT NULL,
    [UserId]               BIGINT              NULL,
    [DeviceId]             NVARCHAR (150)   NULL,
    [DeviceTypeId]         INT              NULL,
    [IsLogOn]              BIT              CONSTRAINT [DF_UserLogin_IsLogin] DEFAULT ((1)) NULL,
    [BuildVersion]         NVARCHAR (15)    NOT NULL,
    [RefreshToken]        UNIQUEIDENTIFIER CONSTRAINT [DF_UserLogin_RefereshToken] DEFAULT (newid()) NULL,
    [IsCurrent]            BIT              CONSTRAINT [DF_UserLogin_IsCurrent] DEFAULT ((1)) NULL,
    [LogOffDate]           DATETIME         NULL,
    [LogOnDate]            DATETIME         NULL,
    [ip]                   NVARCHAR (30)    NULL,
    [city]                 NVARCHAR (50)    NULL,
    [country_name]         NVARCHAR (50)    NULL,
    [organisation]         NVARCHAR (50)    NULL,
    [OsName]               NVARCHAR (50)    NULL,
    [BrowserName]          NVARCHAR (50)    NULL,
    [LastActivityDateTime] DATETIME         CONSTRAINT [DF_UserLogin_LastActivityDateTime] DEFAULT (getutcdate()) NULL,
    [IsFaildLogin] BIT NULL DEFAULT 0, 
    [UserName] NVARCHAR(50) NULL, 
    [IsNewDevice] BIT NULL DEFAULT 0, 
    [OrgKey] UNIQUEIDENTIFIER NULL, 
    [LastLoginURL] NVARCHAR(50) NULL, 
    [DeviceType] NVARCHAR(50) NULL, 
    [LoginProvider] NVARCHAR(500) NULL, 
    CONSTRAINT [PK_UserLogin] PRIMARY KEY CLUSTERED ([UserLoginId] ASC),
    CONSTRAINT [FK_UserLogin_DeviceTypes] FOREIGN KEY ([DeviceTypeId]) REFERENCES [dbo].[DeviceTypes] ([DeviceTypeId]),
    CONSTRAINT [FK_UserLogin_UserLogin] FOREIGN KEY ([UserLoginId]) REFERENCES [dbo].[UserLogin] ([UserLoginId]),
    CONSTRAINT [FK_UserLogin_UserProfile] FOREIGN KEY ([UserId]) REFERENCES [dbo].[UserProfile] ([UserId])
);

