//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCF.Web.Localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCF.Web.Localize.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Update successfully..
        /// </summary>
        public static string Building_Update_Sucess {
            get {
                return ResourceManager.GetString("Building_Update_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password is Incorrect.
        /// </summary>
        public static string Current_Password_NotMatch_With_Password {
            get {
                return ResourceManager.GetString("Current_Password_NotMatch_With_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Deleted successfully..
        /// </summary>
        public static string Delete_Building_Success {
            get {
                return ResourceManager.GetString("Delete_Building_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Deleted successfully..
        /// </summary>
        public static string Delete_floor_Success {
            get {
                return ResourceManager.GetString("Delete_floor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Deleted successfully..
        /// </summary>
        public static string Delete_Profile_Success {
            get {
                return ResourceManager.GetString("Delete_Profile_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check input..
        /// </summary>
        public static string EOP_Update_Error {
            get {
                return ResourceManager.GetString("EOP_Update_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EP Update successfully..
        /// </summary>
        public static string EOP_Update_Sucess {
            get {
                return ResourceManager.GetString("EOP_Update_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we don&apos;t recognize this email address..
        /// </summary>
        public static string Error_Authentication_Msg {
            get {
                return ResourceManager.GetString("Error_Authentication_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Inserted successfully..
        /// </summary>
        public static string Insert_Building_Success {
            get {
                return ResourceManager.GetString("Insert_Building_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Inserted successfully..
        /// </summary>
        public static string Insert_floor_Success {
            get {
                return ResourceManager.GetString("Insert_floor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Created Successfully..
        /// </summary>
        public static string Insert_Profile_Success {
            get {
                return ResourceManager.GetString("Insert_Profile_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Date.
        /// </summary>
        public static string InspectionDate {
            get {
                return ResourceManager.GetString("InspectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string Invalid_User_Login {
            get {
                return ResourceManager.GetString("Invalid_User_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found.
        /// </summary>
        public static string No_Record_Msg {
            get {
                return ResourceManager.GetString("No_Record_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed successfully..
        /// </summary>
        public static string Password_Change_Success {
            get {
                return ResourceManager.GetString("Password_Change_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery instruction was not sent to.
        /// </summary>
        public static string Recovery_Error {
            get {
                return ResourceManager.GetString("Recovery_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery instruction was sent to.
        /// </summary>
        public static string Recovery_Success {
            get {
                return ResourceManager.GetString("Recovery_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Updated successfully..
        /// </summary>
        public static string Update_Building_Success {
            get {
                return ResourceManager.GetString("Update_Building_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Updated successfully..
        /// </summary>
        public static string Update_floor_Success {
            get {
                return ResourceManager.GetString("Update_floor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Updated successfully..
        /// </summary>
        public static string Update_Profile_Success {
            get {
                return ResourceManager.GetString("Update_Profile_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wing added successfully..
        /// </summary>
        public static string Wing_Add_Sucess {
            get {
                return ResourceManager.GetString("Wing_Add_Sucess", resourceCulture);
            }
        }
    }
}
