//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCF.Web.Localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCF.Web.Localize.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Dashboard.
        /// </summary>
        public static string ActivityDashboard {
            get {
                return ResourceManager.GetString("ActivityDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string ActivityDashboard_Dashboard {
            get {
                return ResourceManager.GetString("ActivityDashboard_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Building.
        /// </summary>
        public static string AddBuilding {
            get {
                return ResourceManager.GetString("AddBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add CRA.
        /// </summary>
        public static string AddCRA {
            get {
                return ResourceManager.GetString("AddCRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Facilities Maintenance Occurrence.
        /// </summary>
        public static string AddFacilitiesMaintenanceOccurrence {
            get {
                return ResourceManager.GetString("AddFacilitiesMaintenanceOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Floor.
        /// </summary>
        public static string AddFloor {
            get {
                return ResourceManager.GetString("AddFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Hot Work Permit.
        /// </summary>
        public static string AddHotWorkPermit {
            get {
                return ResourceManager.GetString("AddHotWorkPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Method of Procedure.
        /// </summary>
        public static string AddMethodofProcedure {
            get {
                return ResourceManager.GetString("AddMethodofProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PCRA.
        /// </summary>
        public static string AddPCRA {
            get {
                return ResourceManager.GetString("AddPCRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Property.
        /// </summary>
        public static string AddProperty {
            get {
                return ResourceManager.GetString("AddProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Site.
        /// </summary>
        public static string AddSite {
            get {
                return ResourceManager.GetString("AddSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User Group.
        /// </summary>
        public static string AddUserGroup {
            get {
                return ResourceManager.GetString("AddUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Wing.
        /// </summary>
        public static string AddWing {
            get {
                return ResourceManager.GetString("AddWing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        public static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Code.
        /// </summary>
        public static string AssetCode {
            get {
                return ResourceManager.GetString("AssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Summary.
        /// </summary>
        public static string AssetEpsTitle {
            get {
                return ResourceManager.GetString("AssetEpsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset History.
        /// </summary>
        public static string AssetHistory {
            get {
                return ResourceManager.GetString("AssetHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Name.
        /// </summary>
        public static string AssetName {
            get {
                return ResourceManager.GetString("AssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset #.
        /// </summary>
        public static string AssetNo {
            get {
                return ResourceManager.GetString("AssetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Sub Type.
        /// </summary>
        public static string AssetSubType {
            get {
                return ResourceManager.GetString("AssetSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type.
        /// </summary>
        public static string AssetType {
            get {
                return ResourceManager.GetString("AssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Goal.
        /// </summary>
        public static string AssignGoal {
            get {
                return ResourceManager.GetString("AssignGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binder.
        /// </summary>
        public static string Binder {
            get {
                return ResourceManager.GetString("Binder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Name.
        /// </summary>
        public static string BuildingName {
            get {
                return ResourceManager.GetString("BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Points.
        /// </summary>
        public static string CheckPoints {
            get {
                return ResourceManager.GetString("CheckPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Date.
        /// </summary>
        public static string CompletedDate {
            get {
                return ResourceManager.GetString("CompletedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliant.
        /// </summary>
        public static string CompliantText {
            get {
                return ResourceManager.GetString("CompliantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new work order.
        /// </summary>
        public static string CreateWorkOrder {
            get {
                return ResourceManager.GetString("CreateWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRx Inbox.
        /// </summary>
        public static string CRxInboxTitle {
            get {
                return ResourceManager.GetString("CRxInboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc Required.
        /// </summary>
        public static string DocRequired {
            get {
                return ResourceManager.GetString("DocRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EP.
        /// </summary>
        public static string EP {
            get {
                return ResourceManager.GetString("EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Assets.
        /// </summary>
        public static string FloorAssets {
            get {
                return ResourceManager.GetString("FloorAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Name.
        /// </summary>
        public static string FloorName {
            get {
                return ResourceManager.GetString("FloorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Plan.
        /// </summary>
        public static string FloorPlan {
            get {
                return ResourceManager.GetString("FloorPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILSM Date.
        /// </summary>
        public static string ILSMDate {
            get {
                return ResourceManager.GetString("ILSMDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident #.
        /// </summary>
        public static string IncidentNo {
            get {
                return ResourceManager.GetString("IncidentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Date.
        /// </summary>
        public static string InspectionDate {
            get {
                return ResourceManager.GetString("InspectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Date/Time.
        /// </summary>
        public static string InspectionDateTime {
            get {
                return ResourceManager.GetString("InspectionDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspector.
        /// </summary>
        public static string Inspector {
            get {
                return ResourceManager.GetString("Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspector Name.
        /// </summary>
        public static string InspectorName {
            get {
                return ResourceManager.GetString("InspectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Inspection.
        /// </summary>
        public static string LastInspectionDate {
            get {
                return ResourceManager.GetString("LastInspectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked Deficiency.
        /// </summary>
        public static string MarkedDeficiency {
            get {
                return ResourceManager.GetString("MarkedDeficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby.
        /// </summary>
        public static string NearBy {
            get {
                return ResourceManager.GetString("NearBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Standard.
        /// </summary>
        public static string NewStandard {
            get {
                return ResourceManager.GetString("NewStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string NextDueDate {
            get {
                return ResourceManager.GetString("NextDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Inspection Date.
        /// </summary>
        public static string NextInspectionDate {
            get {
                return ResourceManager.GetString("NextInspectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Compliant.
        /// </summary>
        public static string NonCompliantText {
            get {
                return ResourceManager.GetString("NonCompliantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Floor.
        /// </summary>
        public static string NoOfFloor {
            get {
                return ResourceManager.GetString("NoOfFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Wing.
        /// </summary>
        public static string NoOfWings {
            get {
                return ResourceManager.GetString("NoOfWings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Yet Assigned.
        /// </summary>
        public static string PermitNumber {
            get {
                return ResourceManager.GetString("PermitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated by.
        /// </summary>
        public static string PrintGeneratedByTitle {
            get {
                return ResourceManager.GetString("PrintGeneratedByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Date.
        /// </summary>
        public static string PrintGeneratedDateTitle {
            get {
                return ResourceManager.GetString("PrintGeneratedDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRx.
        /// </summary>
        public static string PrintGeneratedFromText {
            get {
                return ResourceManager.GetString("PrintGeneratedFromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated from.
        /// </summary>
        public static string PrintGeneratedFromTitle {
            get {
                return ResourceManager.GetString("PrintGeneratedFromTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        public static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRx.
        /// </summary>
        public static string ProjectTitle {
            get {
                return ResourceManager.GetString("ProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyType.
        /// </summary>
        public static string PropertyType {
            get {
                return ResourceManager.GetString("PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester.
        /// </summary>
        public static string Requester {
            get {
                return ResourceManager.GetString("Requester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        public static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk.
        /// </summary>
        public static string Risk {
            get {
                return ResourceManager.GetString("Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds &amp; Drills.
        /// </summary>
        public static string RoundDrills {
            get {
                return ResourceManager.GetString("RoundDrills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order.
        /// </summary>
        public static string ServicesRequest {
            get {
                return ResourceManager.GetString("ServicesRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard,EP.
        /// </summary>
        public static string StandardEP {
            get {
                return ResourceManager.GetString("StandardEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Code.
        /// </summary>
        public static string StopCode {
            get {
                return ResourceManager.GetString("StopCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Name.
        /// </summary>
        public static string StopName {
            get {
                return ResourceManager.GetString("StopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time To Resolve it.
        /// </summary>
        public static string TimeToResolveit {
            get {
                return ResourceManager.GetString("TimeToResolveit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add EP.
        /// </summary>
        public static string TitleAddEP {
            get {
                return ResourceManager.GetString("TitleAddEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string TitleAddGoalDetails {
            get {
                return ResourceManager.GetString("TitleAddGoalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question PCRA.
        /// </summary>
        public static string TitleAddQuestionPCRA {
            get {
                return ResourceManager.GetString("TitleAddQuestionPCRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Assets.
        /// </summary>
        public static string TitleAssets {
            get {
                return ResourceManager.GetString("TitleAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add AssetsType.
        /// </summary>
        public static string TitleAssetsType {
            get {
                return ResourceManager.GetString("TitleAssetsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildings.
        /// </summary>
        public static string TitleBuilding {
            get {
                return ResourceManager.GetString("TitleBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string TitleCreateUser {
            get {
                return ResourceManager.GetString("TitleCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vendor.
        /// </summary>
        public static string TitleCreateVendor {
            get {
                return ResourceManager.GetString("TitleCreateVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deficiencies.
        /// </summary>
        public static string TitleDeficiencies {
            get {
                return ResourceManager.GetString("TitleDeficiencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floors.
        /// </summary>
        public static string TitleFloors {
            get {
                return ResourceManager.GetString("TitleFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string TitleForgotPassword {
            get {
                return ResourceManager.GetString("TitleForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacilitiesMaintenanceOccurrence.
        /// </summary>
        public static string TitleGetFacilitiesMaintenanceOccurrence {
            get {
                return ResourceManager.GetString("TitleGetFacilitiesMaintenanceOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Of Procedure.
        /// </summary>
        public static string TitleGetMOP {
            get {
                return ResourceManager.GetString("TitleGetMOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRA.
        /// </summary>
        public static string TitleGetTCRA {
            get {
                return ResourceManager.GetString("TitleGetTCRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Work Permit.
        /// </summary>
        public static string TitleGetTHWP {
            get {
                return ResourceManager.GetString("TitleGetTHWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCRA.
        /// </summary>
        public static string TitleGetTPCRA {
            get {
                return ResourceManager.GetString("TitleGetTPCRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TitleHome {
            get {
                return ResourceManager.GetString("TitleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Safety Device.
        /// </summary>
        public static string TitleLifeSafetyDeviceList {
            get {
                return ResourceManager.GetString("TitleLifeSafetyDeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage EP.
        /// </summary>
        public static string TitleManageEP {
            get {
                return ResourceManager.GetString("TitleManageEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string TitleMyProfile {
            get {
                return ResourceManager.GetString("TitleMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string TitleNews {
            get {
                return ResourceManager.GetString("TitleNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string TitleProperty {
            get {
                return ResourceManager.GetString("TitleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestionDetails PCRA.
        /// </summary>
        public static string TitleQuestionDetailsPCRA {
            get {
                return ResourceManager.GetString("TitleQuestionDetailsPCRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question PCRA.
        /// </summary>
        public static string TitleQuestionPCRA {
            get {
                return ResourceManager.GetString("TitleQuestionPCRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Password.
        /// </summary>
        public static string TitleRecoverPassword {
            get {
                return ResourceManager.GetString("TitleRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string TitleSite {
            get {
                return ResourceManager.GetString("TitleSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string TitleSystem {
            get {
                return ResourceManager.GetString("TitleSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string TitleUpdatePassword {
            get {
                return ResourceManager.GetString("TitleUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string TitleUser {
            get {
                return ResourceManager.GetString("TitleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        public static string TitleUserGroup {
            get {
                return ResourceManager.GetString("TitleUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        public static string TitleVendor {
            get {
                return ResourceManager.GetString("TitleVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wings.
        /// </summary>
        public static string TitleWing {
            get {
                return ResourceManager.GetString("TitleWing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Orders.
        /// </summary>
        public static string TitleWorkOrder {
            get {
                return ResourceManager.GetString("TitleWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Asset.
        /// </summary>
        public static string UpdateAsset {
            get {
                return ResourceManager.GetString("UpdateAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Asset Type.
        /// </summary>
        public static string UpdateAssetType {
            get {
                return ResourceManager.GetString("UpdateAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Building.
        /// </summary>
        public static string UpdateBuilding {
            get {
                return ResourceManager.GetString("UpdateBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string UpdateEditProfile {
            get {
                return ResourceManager.GetString("UpdateEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Standard.
        /// </summary>
        public static string UpdateEditStandard {
            get {
                return ResourceManager.GetString("UpdateEditStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Floor.
        /// </summary>
        public static string UpdateFloors {
            get {
                return ResourceManager.GetString("UpdateFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Property.
        /// </summary>
        public static string UpdateProperty {
            get {
                return ResourceManager.GetString("UpdateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User Group.
        /// </summary>
        public static string UpdateUserGroup {
            get {
                return ResourceManager.GetString("UpdateUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Wing.
        /// </summary>
        public static string UpdateWing {
            get {
                return ResourceManager.GetString("UpdateWing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Permission.
        /// </summary>
        public static string UserPermission {
            get {
                return ResourceManager.GetString("UserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wing.
        /// </summary>
        public static string Wing {
            get {
                return ResourceManager.GetString("Wing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order.
        /// </summary>
        public static string WorkOrder {
            get {
                return ResourceManager.GetString("WorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order #.
        /// </summary>
        public static string WorkOrderNo {
            get {
                return ResourceManager.GetString("WorkOrderNo", resourceCulture);
            }
        }
    }
}
