//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbiDepartmentsWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.frsoft.com/webservices", ConfigurationName="NbiDepartmentsWS.DepartmentWS")]
    public interface DepartmentWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/Load", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Department[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiDepartmentsWS.Department[]> LoadAsync(NbiDepartmentsWS.AuthenticationHeader header, string departmentCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/LoadWithSegment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Department[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiDepartmentsWS.Department> LoadWithSegmentAsync(NbiDepartmentsWS.AuthenticationHeader header, string departmentCode, int segmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Department[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiDepartmentsWS.Department> SaveAsync(NbiDepartmentsWS.AuthenticationHeader header, NbiDepartmentsWS.Department myDepartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/Query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Department[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiDepartmentsWS.Department[]> QueryAsync(NbiDepartmentsWS.AuthenticationHeader header, NbiDepartmentsWS.DepartmentCriteria[] criterias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/QueryWithSegment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Department[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiDepartmentsWS.Department[]> QueryWithSegmentAsync(NbiDepartmentsWS.AuthenticationHeader header, NbiDepartmentsWS.DepartmentCriteria[] criterias, int segmentID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public partial class AuthenticationHeader
    {
        
        private string serverField;
        
        private string databaseField;
        
        private string userNameField;
        
        private string passwordField;
        
        private string passKeyField;
        
        private string hostNameField;
        
        private string openObjectIdField;
        
        private bool useSSOAuthenticationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Server
        {
            get
            {
                return this.serverField;
            }
            set
            {
                this.serverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Database
        {
            get
            {
                return this.databaseField;
            }
            set
            {
                this.databaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PassKey
        {
            get
            {
                return this.passKeyField;
            }
            set
            {
                this.passKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string HostName
        {
            get
            {
                return this.hostNameField;
            }
            set
            {
                this.hostNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string OpenObjectId
        {
            get
            {
                return this.openObjectIdField;
            }
            set
            {
                this.openObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool UseSSOAuthentication
        {
            get
            {
                return this.useSSOAuthenticationField;
            }
            set
            {
                this.useSSOAuthenticationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DepartmentCriteria))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public abstract partial class Criteria
    {
        
        private LOGICAL_OPERATORS logicalOperatorField;
        
        private OPERATORS operatorField;
        
        private object fieldValueField;
        
        private DATA_TYPE_ENUM dataTypeField;
        
        private int fieldIDField;
        
        private string fieldNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LOGICAL_OPERATORS LogicalOperator
        {
            get
            {
                return this.logicalOperatorField;
            }
            set
            {
                this.logicalOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OPERATORS Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object FieldValue
        {
            get
            {
                return this.fieldValueField;
            }
            set
            {
                this.fieldValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DATA_TYPE_ENUM DataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int FieldID
        {
            get
            {
                return this.fieldIDField;
            }
            set
            {
                this.fieldIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FieldName
        {
            get
            {
                return this.fieldNameField;
            }
            set
            {
                this.fieldNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public enum LOGICAL_OPERATORS
    {
        
        /// <remarks/>
        AND,
        
        /// <remarks/>
        OR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public enum OPERATORS
    {
        
        /// <remarks/>
        EQUAL,
        
        /// <remarks/>
        NOT_EQUAL,
        
        /// <remarks/>
        ISLIKE,
        
        /// <remarks/>
        GREATER,
        
        /// <remarks/>
        LESS,
        
        /// <remarks/>
        GREATER_OR_EQUAL,
        
        /// <remarks/>
        LESS_OR_EQUAL,
        
        /// <remarks/>
        ISNULL,
        
        /// <remarks/>
        ISNOTLIKE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public enum DATA_TYPE_ENUM
    {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        STRING,
        
        /// <remarks/>
        NUMBER,
        
        /// <remarks/>
        BOOLEAN,
        
        /// <remarks/>
        DATE,
        
        /// <remarks/>
        TIME,
        
        /// <remarks/>
        EMAIL,
        
        /// <remarks/>
        CURRENCY,
        
        /// <remarks/>
        PERCENT,
        
        /// <remarks/>
        OBJECT,
        
        /// <remarks/>
        WHOLE_NUMBER,
        
        /// <remarks/>
        DATE_TIME,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public partial class DepartmentCriteria : Criteria
    {
        
        private FIELDS fieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FIELDS Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public enum FIELDS
    {
        
        /// <remarks/>
        DEPARTMENT_CODE,
        
        /// <remarks/>
        FACILITY,
        
        /// <remarks/>
        FACILITY_MANAGER,
        
        /// <remarks/>
        FACILITY_LOCATION,
        
        /// <remarks/>
        DEPARTMENT_NAME,
        
        /// <remarks/>
        ADDRESS1,
        
        /// <remarks/>
        ADDRESS2,
        
        /// <remarks/>
        CITY,
        
        /// <remarks/>
        STATE,
        
        /// <remarks/>
        ZIP,
        
        /// <remarks/>
        COUNTRY,
        
        /// <remarks/>
        UDF1,
        
        /// <remarks/>
        UDF2,
        
        /// <remarks/>
        UDF3,
        
        /// <remarks/>
        UDF4,
        
        /// <remarks/>
        UDF5,
        
        /// <remarks/>
        UDF6,
        
        /// <remarks/>
        UDF7,
        
        /// <remarks/>
        UDF8,
        
        /// <remarks/>
        UDF9,
        
        /// <remarks/>
        UDF10,
        
        /// <remarks/>
        TYPE_CODE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public partial class CustomField
    {
        
        private int fieldIdField;
        
        private int parentFieldIdField;
        
        private string nameField;
        
        private object valueField;
        
        private string valueDescriptionField;
        
        private bool isCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FieldId
        {
            get
            {
                return this.fieldIdField;
            }
            set
            {
                this.fieldIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ParentFieldId
        {
            get
            {
                return this.parentFieldIdField;
            }
            set
            {
                this.parentFieldIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public object Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ValueDescription
        {
            get
            {
                return this.valueDescriptionField;
            }
            set
            {
                this.valueDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsCode
        {
            get
            {
                return this.isCodeField;
            }
            set
            {
                this.isCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Department))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public abstract partial class SDKBase
    {
        
        private int segmentIDField;
        
        private int fieldIdField;
        
        private MODULES moduleIdField;
        
        private bool validateForDataImportField;
        
        private int keyIDField;
        
        private CustomField[] customFieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SegmentID
        {
            get
            {
                return this.segmentIDField;
            }
            set
            {
                this.segmentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int FieldId
        {
            get
            {
                return this.fieldIdField;
            }
            set
            {
                this.fieldIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MODULES ModuleId
        {
            get
            {
                return this.moduleIdField;
            }
            set
            {
                this.moduleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ValidateForDataImport
        {
            get
            {
                return this.validateForDataImportField;
            }
            set
            {
                this.validateForDataImportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int KeyID
        {
            get
            {
                return this.keyIDField;
            }
            set
            {
                this.keyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public CustomField[] CustomFields
        {
            get
            {
                return this.customFieldsField;
            }
            set
            {
                this.customFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public enum MODULES
    {
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        TASKS,
        
        /// <remarks/>
        RESOURCES,
        
        /// <remarks/>
        ASSETS,
        
        /// <remarks/>
        MATERIALS,
        
        /// <remarks/>
        WORK_ORDERS,
        
        /// <remarks/>
        VENDORS,
        
        /// <remarks/>
        TIME_CHARGES,
        
        /// <remarks/>
        PM,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        PURCHASING,
        
        /// <remarks/>
        REPORTING,
        
        /// <remarks/>
        REQUISITIONS,
        
        /// <remarks/>
        PM_GENERATE,
        
        /// <remarks/>
        WEB_REQUEST,
        
        /// <remarks/>
        WO_SURVEY,
        
        /// <remarks/>
        QUICK_CLOSE,
        
        /// <remarks/>
        EMAIL_RESPONSE,
        
        /// <remarks/>
        UPGRADE,
        
        /// <remarks/>
        GENERAL,
        
        /// <remarks/>
        DOCUMENT_UPLOAD,
        
        /// <remarks/>
        CONTRACTS,
        
        /// <remarks/>
        PO_GENERATE,
        
        /// <remarks/>
        REQUISITION_GENERATE,
        
        /// <remarks/>
        REQUESTERS,
        
        /// <remarks/>
        CUSTOMERS,
        
        /// <remarks/>
        BLANKET_ORDERS,
        
        /// <remarks/>
        SUB_TASKS,
        
        /// <remarks/>
        DISPATCH,
        
        /// <remarks/>
        DEPARTMENTS,
        
        /// <remarks/>
        UTILITY,
        
        /// <remarks/>
        SAFETY_INCIDENTS,
        
        /// <remarks/>
        INFO_CENTER,
        
        /// <remarks/>
        HIS_LINKS,
        
        /// <remarks/>
        HL7,
        
        /// <remarks/>
        SDK,
        
        /// <remarks/>
        AUTOPRINT,
        
        /// <remarks/>
        ASSET_GROUPS,
        
        /// <remarks/>
        TASK_GROUPS,
        
        /// <remarks/>
        MED_TESTER,
        
        /// <remarks/>
        HIPAA_SURVEY,
        
        /// <remarks/>
        AUTO_ASSIGNMENT,
        
        /// <remarks/>
        ECRI_ALERTS,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        SOURCEBASE_CODES,
        
        /// <remarks/>
        UMDNS_CODES,
        
        /// <remarks/>
        CONTRACT_PAYMENTS,
        
        /// <remarks/>
        CUSTOMER_CONTACTS,
        
        /// <remarks/>
        DASHBOARD,
        
        /// <remarks/>
        DISCUSSIONS,
        
        /// <remarks/>
        MATERIAL_ISSUES,
        
        /// <remarks/>
        MATERIAL_RECEIPTS,
        
        /// <remarks/>
        DOWNTIMES,
        
        /// <remarks/>
        USER_FIELDS,
        
        /// <remarks/>
        WO_TASKS,
        
        /// <remarks/>
        WO_ASSIGNMENTS,
        
        /// <remarks/>
        ASSET_CONTACTS,
        
        /// <remarks/>
        ASSET_COMPONENTS,
        
        /// <remarks/>
        WO_ASSETS,
        
        /// <remarks/>
        PM_ASSETS,
        
        /// <remarks/>
        CONTRACT_ASSETS,
        
        /// <remarks/>
        ASSET_MATERIALS,
        
        /// <remarks/>
        PM_MATERIALS,
        
        /// <remarks/>
        PARTS_SOURCE,
        
        /// <remarks/>
        DATASOURCE,
        
        /// <remarks/>
        SAVED_QUERIES,
        
        /// <remarks/>
        REPORT_DEFINITIONS,
        
        /// <remarks/>
        PM_ASSIGNMENTS,
        
        /// <remarks/>
        PM_EXCEPTIONS,
        
        /// <remarks/>
        PM_PROCEDURES,
        
        /// <remarks/>
        TASK_MATERIALS,
        
        /// <remarks/>
        VENDOR_MODELS,
        
        /// <remarks/>
        PATIENT,
        
        /// <remarks/>
        USER_PROFILES,
        
        /// <remarks/>
        PORTALS,
        
        /// <remarks/>
        INSPECTIONS,
        
        /// <remarks/>
        SEGMENTS,
        
        /// <remarks/>
        MESSAGE_CENTER,
        
        /// <remarks/>
        SEGMENTFIELDS,
        
        /// <remarks/>
        STORED_PROCEDURE_SCHEDULE,
        
        /// <remarks/>
        SCHEDULES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public partial class Department : SDKBase
    {
        
        private string departmentCodeField;
        
        private string departmentNameField;
        
        private string facilityField;
        
        private string facilityManagerField;
        
        private string facilityLocationField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string countryField;
        
        private string uDF1Field;
        
        private string uDF2Field;
        
        private string uDF3Field;
        
        private string uDF4Field;
        
        private string uDF5Field;
        
        private string uDF6Field;
        
        private string uDF7Field;
        
        private string uDF8Field;
        
        private string uDF9Field;
        
        private string uDF10Field;
        
        private string typeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DepartmentCode
        {
            get
            {
                return this.departmentCodeField;
            }
            set
            {
                this.departmentCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DepartmentName
        {
            get
            {
                return this.departmentNameField;
            }
            set
            {
                this.departmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Facility
        {
            get
            {
                return this.facilityField;
            }
            set
            {
                this.facilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FacilityManager
        {
            get
            {
                return this.facilityManagerField;
            }
            set
            {
                this.facilityManagerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FacilityLocation
        {
            get
            {
                return this.facilityLocationField;
            }
            set
            {
                this.facilityLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string UDF1
        {
            get
            {
                return this.uDF1Field;
            }
            set
            {
                this.uDF1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string UDF2
        {
            get
            {
                return this.uDF2Field;
            }
            set
            {
                this.uDF2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string UDF3
        {
            get
            {
                return this.uDF3Field;
            }
            set
            {
                this.uDF3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string UDF4
        {
            get
            {
                return this.uDF4Field;
            }
            set
            {
                this.uDF4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string UDF5
        {
            get
            {
                return this.uDF5Field;
            }
            set
            {
                this.uDF5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string UDF6
        {
            get
            {
                return this.uDF6Field;
            }
            set
            {
                this.uDF6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string UDF7
        {
            get
            {
                return this.uDF7Field;
            }
            set
            {
                this.uDF7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string UDF8
        {
            get
            {
                return this.uDF8Field;
            }
            set
            {
                this.uDF8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string UDF9
        {
            get
            {
                return this.uDF9Field;
            }
            set
            {
                this.uDF9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string UDF10
        {
            get
            {
                return this.uDF10Field;
            }
            set
            {
                this.uDF10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string TypeCode
        {
            get
            {
                return this.typeCodeField;
            }
            set
            {
                this.typeCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface DepartmentWSChannel : NbiDepartmentsWS.DepartmentWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DepartmentWSClient : System.ServiceModel.ClientBase<NbiDepartmentsWS.DepartmentWS>, NbiDepartmentsWS.DepartmentWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DepartmentWSClient(EndpointConfiguration endpointConfiguration) : 
                base(DepartmentWSClient.GetBindingForEndpoint(endpointConfiguration), DepartmentWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DepartmentWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DepartmentWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DepartmentWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DepartmentWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DepartmentWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<NbiDepartmentsWS.Department[]> LoadAsync(NbiDepartmentsWS.AuthenticationHeader header, string departmentCode)
        {
            return base.Channel.LoadAsync(header, departmentCode);
        }
        
        public System.Threading.Tasks.Task<NbiDepartmentsWS.Department> LoadWithSegmentAsync(NbiDepartmentsWS.AuthenticationHeader header, string departmentCode, int segmentID)
        {
            return base.Channel.LoadWithSegmentAsync(header, departmentCode, segmentID);
        }
        
        public System.Threading.Tasks.Task<NbiDepartmentsWS.Department> SaveAsync(NbiDepartmentsWS.AuthenticationHeader header, NbiDepartmentsWS.Department myDepartment)
        {
            return base.Channel.SaveAsync(header, myDepartment);
        }
        
        public System.Threading.Tasks.Task<NbiDepartmentsWS.Department[]> QueryAsync(NbiDepartmentsWS.AuthenticationHeader header, NbiDepartmentsWS.DepartmentCriteria[] criterias)
        {
            return base.Channel.QueryAsync(header, criterias);
        }
        
        public System.Threading.Tasks.Task<NbiDepartmentsWS.Department[]> QueryWithSegmentAsync(NbiDepartmentsWS.AuthenticationHeader header, NbiDepartmentsWS.DepartmentCriteria[] criterias, int segmentID)
        {
            return base.Channel.QueryWithSegmentAsync(header, criterias, segmentID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DepartmentWS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DepartmentWS1))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DepartmentWS))
            {
                return new System.ServiceModel.EndpointAddress("https://rwjbh.tmsonline.com/tmsconnect/DepartmentWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DepartmentWS1))
            {
                return new System.ServiceModel.EndpointAddress("https://rwjbh.tmsonline.com/tmsconnect/DepartmentWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DepartmentWS,
            
            DepartmentWS1,
        }
    }
}
