//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbiRequesterWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.frsoft.com/webservices", ConfigurationName="NbiRequesterWS.RequesterWS")]
    public interface RequesterWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/Load", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Requester[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiRequesterWS.Requester[]> LoadAsync(NbiRequesterWS.AuthenticationHeader header, string requester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/LoadWithSegment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Requester[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiRequesterWS.Requester> LoadWithSegmentAsync(NbiRequesterWS.AuthenticationHeader header, string requester, int segmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Requester[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiRequesterWS.Requester> SaveAsync(NbiRequesterWS.AuthenticationHeader header, NbiRequesterWS.Requester r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/Query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Requester[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiRequesterWS.Requester[]> QueryAsync(NbiRequesterWS.AuthenticationHeader header, NbiRequesterWS.RequesterCriteria[] criteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.frsoft.com/webservices/QueryWithSegment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Criteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SDKBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Requester[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomField[]))]
        System.Threading.Tasks.Task<NbiRequesterWS.Requester[]> QueryWithSegmentAsync(NbiRequesterWS.AuthenticationHeader header, NbiRequesterWS.RequesterCriteria[] criteria, int segmentID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public partial class AuthenticationHeader
    {
        
        private string serverField;
        
        private string databaseField;
        
        private string userNameField;
        
        private string passwordField;
        
        private string passKeyField;
        
        private string hostNameField;
        
        private string openObjectIdField;
        
        private bool useSSOAuthenticationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Server
        {
            get
            {
                return this.serverField;
            }
            set
            {
                this.serverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Database
        {
            get
            {
                return this.databaseField;
            }
            set
            {
                this.databaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PassKey
        {
            get
            {
                return this.passKeyField;
            }
            set
            {
                this.passKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string HostName
        {
            get
            {
                return this.hostNameField;
            }
            set
            {
                this.hostNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string OpenObjectId
        {
            get
            {
                return this.openObjectIdField;
            }
            set
            {
                this.openObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool UseSSOAuthentication
        {
            get
            {
                return this.useSSOAuthenticationField;
            }
            set
            {
                this.useSSOAuthenticationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequesterCriteria))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public abstract partial class Criteria
    {
        
        private LOGICAL_OPERATORS logicalOperatorField;
        
        private OPERATORS operatorField;
        
        private object fieldValueField;
        
        private DATA_TYPE_ENUM dataTypeField;
        
        private int fieldIDField;
        
        private string fieldNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LOGICAL_OPERATORS LogicalOperator
        {
            get
            {
                return this.logicalOperatorField;
            }
            set
            {
                this.logicalOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OPERATORS Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object FieldValue
        {
            get
            {
                return this.fieldValueField;
            }
            set
            {
                this.fieldValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DATA_TYPE_ENUM DataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int FieldID
        {
            get
            {
                return this.fieldIDField;
            }
            set
            {
                this.fieldIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FieldName
        {
            get
            {
                return this.fieldNameField;
            }
            set
            {
                this.fieldNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public enum LOGICAL_OPERATORS
    {
        
        /// <remarks/>
        AND,
        
        /// <remarks/>
        OR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public enum OPERATORS
    {
        
        /// <remarks/>
        EQUAL,
        
        /// <remarks/>
        NOT_EQUAL,
        
        /// <remarks/>
        ISLIKE,
        
        /// <remarks/>
        GREATER,
        
        /// <remarks/>
        LESS,
        
        /// <remarks/>
        GREATER_OR_EQUAL,
        
        /// <remarks/>
        LESS_OR_EQUAL,
        
        /// <remarks/>
        ISNULL,
        
        /// <remarks/>
        ISNOTLIKE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public enum DATA_TYPE_ENUM
    {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        STRING,
        
        /// <remarks/>
        NUMBER,
        
        /// <remarks/>
        BOOLEAN,
        
        /// <remarks/>
        DATE,
        
        /// <remarks/>
        TIME,
        
        /// <remarks/>
        EMAIL,
        
        /// <remarks/>
        CURRENCY,
        
        /// <remarks/>
        PERCENT,
        
        /// <remarks/>
        OBJECT,
        
        /// <remarks/>
        WHOLE_NUMBER,
        
        /// <remarks/>
        DATE_TIME,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public partial class RequesterCriteria : Criteria
    {
        
        private FIELDS fieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FIELDS Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public enum FIELDS
    {
        
        /// <remarks/>
        SEGMENT,
        
        /// <remarks/>
        EMAIL,
        
        /// <remarks/>
        ACCOUNT_CODE,
        
        /// <remarks/>
        ACCOUNT_DESCRIPTION,
        
        /// <remarks/>
        SITE_CODE,
        
        /// <remarks/>
        SITE_NAME,
        
        /// <remarks/>
        BUILDING_CODE,
        
        /// <remarks/>
        BUILDING_NAME,
        
        /// <remarks/>
        LOCATION_CODE,
        
        /// <remarks/>
        LOCATION_DESCRIPTION,
        
        /// <remarks/>
        REQUESTER_NAME,
        
        /// <remarks/>
        REQUESTER_PHONE_NUMBER,
        
        /// <remarks/>
        REQUESTER_PAGER_NUMBER,
        
        /// <remarks/>
        REQUESTER_ID,
        
        /// <remarks/>
        DATE_UPDATED,
        
        /// <remarks/>
        DATE_CREATED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public partial class CustomField
    {
        
        private int fieldIdField;
        
        private int parentFieldIdField;
        
        private string nameField;
        
        private object valueField;
        
        private string valueDescriptionField;
        
        private bool isCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FieldId
        {
            get
            {
                return this.fieldIdField;
            }
            set
            {
                this.fieldIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ParentFieldId
        {
            get
            {
                return this.parentFieldIdField;
            }
            set
            {
                this.parentFieldIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public object Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ValueDescription
        {
            get
            {
                return this.valueDescriptionField;
            }
            set
            {
                this.valueDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsCode
        {
            get
            {
                return this.isCodeField;
            }
            set
            {
                this.isCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Requester))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public abstract partial class SDKBase
    {
        
        private int segmentIDField;
        
        private int fieldIdField;
        
        private MODULES moduleIdField;
        
        private bool validateForDataImportField;
        
        private int keyIDField;
        
        private CustomField[] customFieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SegmentID
        {
            get
            {
                return this.segmentIDField;
            }
            set
            {
                this.segmentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int FieldId
        {
            get
            {
                return this.fieldIdField;
            }
            set
            {
                this.fieldIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MODULES ModuleId
        {
            get
            {
                return this.moduleIdField;
            }
            set
            {
                this.moduleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ValidateForDataImport
        {
            get
            {
                return this.validateForDataImportField;
            }
            set
            {
                this.validateForDataImportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int KeyID
        {
            get
            {
                return this.keyIDField;
            }
            set
            {
                this.keyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public CustomField[] CustomFields
        {
            get
            {
                return this.customFieldsField;
            }
            set
            {
                this.customFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public enum MODULES
    {
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        TASKS,
        
        /// <remarks/>
        RESOURCES,
        
        /// <remarks/>
        ASSETS,
        
        /// <remarks/>
        MATERIALS,
        
        /// <remarks/>
        WORK_ORDERS,
        
        /// <remarks/>
        VENDORS,
        
        /// <remarks/>
        TIME_CHARGES,
        
        /// <remarks/>
        PM,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        PURCHASING,
        
        /// <remarks/>
        REPORTING,
        
        /// <remarks/>
        REQUISITIONS,
        
        /// <remarks/>
        PM_GENERATE,
        
        /// <remarks/>
        WEB_REQUEST,
        
        /// <remarks/>
        WO_SURVEY,
        
        /// <remarks/>
        QUICK_CLOSE,
        
        /// <remarks/>
        EMAIL_RESPONSE,
        
        /// <remarks/>
        UPGRADE,
        
        /// <remarks/>
        GENERAL,
        
        /// <remarks/>
        DOCUMENT_UPLOAD,
        
        /// <remarks/>
        CONTRACTS,
        
        /// <remarks/>
        PO_GENERATE,
        
        /// <remarks/>
        REQUISITION_GENERATE,
        
        /// <remarks/>
        REQUESTERS,
        
        /// <remarks/>
        CUSTOMERS,
        
        /// <remarks/>
        BLANKET_ORDERS,
        
        /// <remarks/>
        SUB_TASKS,
        
        /// <remarks/>
        DISPATCH,
        
        /// <remarks/>
        DEPARTMENTS,
        
        /// <remarks/>
        UTILITY,
        
        /// <remarks/>
        SAFETY_INCIDENTS,
        
        /// <remarks/>
        INFO_CENTER,
        
        /// <remarks/>
        HIS_LINKS,
        
        /// <remarks/>
        HL7,
        
        /// <remarks/>
        SDK,
        
        /// <remarks/>
        AUTOPRINT,
        
        /// <remarks/>
        ASSET_GROUPS,
        
        /// <remarks/>
        TASK_GROUPS,
        
        /// <remarks/>
        MED_TESTER,
        
        /// <remarks/>
        HIPAA_SURVEY,
        
        /// <remarks/>
        AUTO_ASSIGNMENT,
        
        /// <remarks/>
        ECRI_ALERTS,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        SOURCEBASE_CODES,
        
        /// <remarks/>
        UMDNS_CODES,
        
        /// <remarks/>
        CONTRACT_PAYMENTS,
        
        /// <remarks/>
        CUSTOMER_CONTACTS,
        
        /// <remarks/>
        DASHBOARD,
        
        /// <remarks/>
        DISCUSSIONS,
        
        /// <remarks/>
        MATERIAL_ISSUES,
        
        /// <remarks/>
        MATERIAL_RECEIPTS,
        
        /// <remarks/>
        DOWNTIMES,
        
        /// <remarks/>
        USER_FIELDS,
        
        /// <remarks/>
        WO_TASKS,
        
        /// <remarks/>
        WO_ASSIGNMENTS,
        
        /// <remarks/>
        ASSET_CONTACTS,
        
        /// <remarks/>
        ASSET_COMPONENTS,
        
        /// <remarks/>
        WO_ASSETS,
        
        /// <remarks/>
        PM_ASSETS,
        
        /// <remarks/>
        CONTRACT_ASSETS,
        
        /// <remarks/>
        ASSET_MATERIALS,
        
        /// <remarks/>
        PM_MATERIALS,
        
        /// <remarks/>
        PARTS_SOURCE,
        
        /// <remarks/>
        DATASOURCE,
        
        /// <remarks/>
        SAVED_QUERIES,
        
        /// <remarks/>
        REPORT_DEFINITIONS,
        
        /// <remarks/>
        PM_ASSIGNMENTS,
        
        /// <remarks/>
        PM_EXCEPTIONS,
        
        /// <remarks/>
        PM_PROCEDURES,
        
        /// <remarks/>
        TASK_MATERIALS,
        
        /// <remarks/>
        VENDOR_MODELS,
        
        /// <remarks/>
        PATIENT,
        
        /// <remarks/>
        USER_PROFILES,
        
        /// <remarks/>
        PORTALS,
        
        /// <remarks/>
        INSPECTIONS,
        
        /// <remarks/>
        SEGMENTS,
        
        /// <remarks/>
        MESSAGE_CENTER,
        
        /// <remarks/>
        SEGMENTFIELDS,
        
        /// <remarks/>
        STORED_PROCEDURE_SCHEDULE,
        
        /// <remarks/>
        SCHEDULES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.frsoft.com/webservices")]
    public partial class Requester : SDKBase
    {
        
        private string accountCodeField;
        
        private string accountDescriptionField;
        
        private string buildingCodeField;
        
        private string buildingNameField;
        
        private string locationCodeField;
        
        private string locationDescriptionField;
        
        private string siteCodeField;
        
        private string siteNameField;
        
        private string emailField;
        
        private string fullNameField;
        
        private string pagerNumberField;
        
        private string phoneNumberField;
        
        private int requesterIDField;
        
        private string requesterNameField;
        
        private System.Nullable<System.DateTime> dateUpdatedField;
        
        private System.Nullable<System.DateTime> dateCreatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountCode
        {
            get
            {
                return this.accountCodeField;
            }
            set
            {
                this.accountCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AccountDescription
        {
            get
            {
                return this.accountDescriptionField;
            }
            set
            {
                this.accountDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BuildingCode
        {
            get
            {
                return this.buildingCodeField;
            }
            set
            {
                this.buildingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BuildingName
        {
            get
            {
                return this.buildingNameField;
            }
            set
            {
                this.buildingNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LocationCode
        {
            get
            {
                return this.locationCodeField;
            }
            set
            {
                this.locationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LocationDescription
        {
            get
            {
                return this.locationDescriptionField;
            }
            set
            {
                this.locationDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SiteCode
        {
            get
            {
                return this.siteCodeField;
            }
            set
            {
                this.siteCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SiteName
        {
            get
            {
                return this.siteNameField;
            }
            set
            {
                this.siteNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PagerNumber
        {
            get
            {
                return this.pagerNumberField;
            }
            set
            {
                this.pagerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int RequesterID
        {
            get
            {
                return this.requesterIDField;
            }
            set
            {
                this.requesterIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string RequesterName
        {
            get
            {
                return this.requesterNameField;
            }
            set
            {
                this.requesterNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<System.DateTime> DateUpdated
        {
            get
            {
                return this.dateUpdatedField;
            }
            set
            {
                this.dateUpdatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<System.DateTime> DateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface RequesterWSChannel : NbiRequesterWS.RequesterWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class RequesterWSClient : System.ServiceModel.ClientBase<NbiRequesterWS.RequesterWS>, NbiRequesterWS.RequesterWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RequesterWSClient(EndpointConfiguration endpointConfiguration) : 
                base(RequesterWSClient.GetBindingForEndpoint(endpointConfiguration), RequesterWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RequesterWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RequesterWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RequesterWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RequesterWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RequesterWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<NbiRequesterWS.Requester[]> LoadAsync(NbiRequesterWS.AuthenticationHeader header, string requester)
        {
            return base.Channel.LoadAsync(header, requester);
        }
        
        public System.Threading.Tasks.Task<NbiRequesterWS.Requester> LoadWithSegmentAsync(NbiRequesterWS.AuthenticationHeader header, string requester, int segmentID)
        {
            return base.Channel.LoadWithSegmentAsync(header, requester, segmentID);
        }
        
        public System.Threading.Tasks.Task<NbiRequesterWS.Requester> SaveAsync(NbiRequesterWS.AuthenticationHeader header, NbiRequesterWS.Requester r)
        {
            return base.Channel.SaveAsync(header, r);
        }
        
        public System.Threading.Tasks.Task<NbiRequesterWS.Requester[]> QueryAsync(NbiRequesterWS.AuthenticationHeader header, NbiRequesterWS.RequesterCriteria[] criteria)
        {
            return base.Channel.QueryAsync(header, criteria);
        }
        
        public System.Threading.Tasks.Task<NbiRequesterWS.Requester[]> QueryWithSegmentAsync(NbiRequesterWS.AuthenticationHeader header, NbiRequesterWS.RequesterCriteria[] criteria, int segmentID)
        {
            return base.Channel.QueryWithSegmentAsync(header, criteria, segmentID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RequesterWS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.RequesterWS1))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RequesterWS))
            {
                return new System.ServiceModel.EndpointAddress("https://rwjbh.tmsonline.com/tmsconnect/RequesterWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.RequesterWS1))
            {
                return new System.ServiceModel.EndpointAddress("https://rwjbh.tmsonline.com/tmsconnect/RequesterWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            RequesterWS,
            
            RequesterWS1,
        }
    }
}
